// tokeniser.h : shared definition for tokeniser.l and compilateur.cpp

enum TOKEN {FEOF, UNKNOWN, NUMBER, CHARCONST, FLOATCONST, ID, STRINGCONST, RBRACKET, LBRACKET, RPARENT, LPARENT, COMMA, SEMICOLON, DOT, ADDOP, MULOP, RELOP, NOT, ASSIGN, COLON, THEN, ELSE, DO, TO, STEP, END, IF, WHILE, FOR, CASE, OF, BEGIN0, TRUE0, FALSE0, DISPLAY, VAR, BOOLEAN, INTEGER, DOUBLE, CHAR};

